In [1]:
import pandas as pd
file_path = "data.txt"
with open(file_path, "r") as file:
    lines = file.readlines()
        
row_index = 2  
if row_index < len(lines):
            print(lines[row_index])
else:
            print(f"Row {row_index + 1} does not exist in the file.")

15-04-22|00:00:16:637|S|IXN22EKB63500|126|2|1407801633274000101|f1=2|f2=IXN|f4=20|f5=5|f6=2022|f7=635|f8=100|f31=iShares Global Tech ETF|f666=IXN|f677=C|f1663=SQL|f1664=A|f214=3

In [2]:
input_file_path = "data.txt"
output_file_path = "output3.txt"
try:
    with open(input_file_path, "r") as input_file:
        file_content = input_file.read()
        modified_content = file_content.replace("|", ",")

    with open(output_file_path, "w") as output_file:
        output_file.write(modified_content)
        
    print("Data has been processed and saved to the output file.")

except FileNotFoundError:
    print(f"The file '{input_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred: {str(e)}")

Data has been processed and saved to the output file.

In [3]:
import csv

input_file_path = "output3.txt"
output_csv_path = "fileRecap3.csv"

try:
    # Open the input text file for reading
    with open(input_file_path, "r") as input_file:
        # Initialize a list to store the rows
        rows = []

        # Read all lines from the file
        lines = input_file.readlines()

        # Find the maximum number of columns in any line
        max_columns = max(len(line.strip().split('|')) for line in lines)

        # Iterate through each line and pad/truncate to match max_columns
        for line in lines:
            columns = line.strip().split('|')
            if len(columns) < max_columns:
                # Pad the line with empty cells to match max_columns
                columns.extend([''] * (max_columns - len(columns)))
            elif len(columns) > max_columns:
                # Truncate the line to match max_columns
                columns = columns[:max_columns]

            rows.append(columns)

    # Write the rows to the output CSV file
    with open(output_csv_path, "w", newline='') as output_csv:
        csv_writer = csv.writer(output_csv)
        csv_writer.writerows(rows)

    print(f"Text file '{input_file_path}' successfully converted to CSV file '{output_csv_path}'.")

except FileNotFoundError:
    print(f"The file '{input_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred: {str(e)}")
    
column_names=["Courses"]

# Add header row while reading a CSV file
df = pd.read_csv("fileRecap3.csv", names=column_names)
df.to_csv('fileRecap3.csv', index=False)

Text file 'output3.txt' successfully converted to CSV file 'fileRecap3.csv'.

In [4]:

# Splitting combined coloumn into seperate coloumn
csv_file_path = "fileRecap3.csv"

try:
    # Read the CSV file into a pandas dataframe
    df = pd.read_csv(csv_file_path)

    # Split the "Combined_Column" into separate columns
    split_data = df['Courses'].str.split(',', expand=True)

    # Rename the generated columns
    split_data.columns = ['Date', 'Time', 'Message Type', 'Instrument code', 'Exchange Code', 'Security Type', 'Unknown', 'Bid market', 'Bid price', 'Bid size','Ask market','Ask price','Ask size','Message Type1','Message Type2','Message Type3','Message Type4','Message Type5','Message Type6','Message Type7','Message Type8','Message Type9','Message Type9','Message Type9','Message Type9','Message Type9']

    # Concatenate the split data columns with the original dataframe
    df = pd.concat([df, split_data], axis=1)

    # Drop the original "Combined_Column" if no longer needed
    df.drop(columns=['Courses'], inplace=True)

    # Display the modified dataframe
    print(df)

except FileNotFoundError:
    print(f"The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred: {str(e)}")

           Date          Time Message Type Instrument code Exchange Code  \
0      15-04-22  00:00:08:285            S   IXN22EKB61500           126
1      15-04-22  00:00:14:401            S   IXN22BIB63500           126
2      15-04-22  00:00:16:637            S   IXN22EKB63500           126
3      15-04-22  00:00:23:085            S   IXN22QKB61500           126
4      15-04-22  00:00:31:035            S   IXN24AJB64500           126
...         ...           ...          ...             ...           ...
78914  15-04-22  23:59:04:332            S   IXN22EKB20000           126
78915  15-04-22  23:59:44:640            S   IXN22QKB61000           126
78916  15-04-22  23:59:49:329            S   IXN22EKB61000           126
78917  15-04-22  23:59:49:451            S   IXN22EKB60500           126
78918  15-04-22  23:59:52:460            S   IXN22QKB60500           126

      Security Type              Unknown Bid market Bid price Bid size  ...  \
0                 2  1407801616570000200       f1=2    f2=IXN    f4=20  ...
1                 2  1407801628802000306       f1=2    f2=IXN    f4=18  ...
2                 2  1407801633274000101       f1=2    f2=IXN    f4=20  ...
3                 2  1407801646170000213       f1=2    f2=IXN    f4=20  ...
4                 2  1407801662070000122       f1=2    f2=IXN    f4=19  ...
...             ...                  ...        ...       ...      ...  ...
78914             2  1407974288664000019       f1=2    f2=IXN    f4=20  ...
78915             2  1407974369280000003       f1=2    f2=IXN    f4=20  ...
78916             2  1407974378658000007       f1=2    f2=IXN    f4=20  ...
78917             2  1407974378902000003       f1=2    f2=IXN    f4=20  ...
78918             2  1407974384920000009       f1=2    f2=IXN    f4=20  ...

      Message Type4 Message Type5 Message Type6 Message Type7 Message Type8  \
0            f677=C     f1663=SQL       f1664=A        f214=3          None
1            f677=C     f1663=SQL       f1664=A        f214=3          None
2            f677=C     f1663=SQL       f1664=A        f214=3          None
3            f677=P     f1663=SQL       f1664=A        f214=3          None
4            f677=C     f1663=SQL       f1664=A        f214=3          None
...             ...           ...           ...           ...           ...
78914        f677=C     f1663=SQL       f1664=A        f214=3          None
78915        f677=P     f1663=SQL       f1664=A        f214=3          None
78916        f677=C     f1663=SQL       f1664=A        f214=3          None
78917        f677=C     f1663=SQL       f1664=A        f214=3          None
78918        f677=P     f1663=SQL       f1664=A        f214=3          None

      Message Type9 Message Type9 Message Type9 Message Type9 Message Type9
0              None          None          None          None          None
1              None          None          None          None          None
2              None          None          None          None          None
3              None          None          None          None          None
4              None          None          None          None          None
...             ...           ...           ...           ...           ...
78914          None          None          None          None          None
78915          None          None          None          None          None
78916          None          None          None          None          None
78917          None          None          None          None          None
78918          None          None          None          None          None

[78919 rows x 26 columns]

In [5]:
character_to_keep = 'T'

# Use boolean indexing to keep rows where 'Column1' contains the character
filtered_df = df[df['Message Type'].str.contains(character_to_keep)]

# Specify the file path for the CSV output
output_csv_path = "finalTdata.csv"

# Save the filtered data to a new CSV file
filtered_df.to_csv(output_csv_path, index=False)

# Display the resulting DataFrame with only the desired rows
print(filtered_df)

           Date          Time Message Type Instrument code Exchange Code  \
4014   15-04-22  13:30:09:277            T   IXN22FHB34000           126
4015   15-04-22  13:30:09:277            T   IXN22FHB34000           126
5269   15-04-22  13:33:41:714            T   IXN22QKB28000           126
7184   15-04-22  13:51:06:061            T   IXN22FHB33500           126
8223   15-04-22  13:58:00:999            T   IXN22UGB30000           126
...         ...           ...          ...             ...           ...
74667  15-04-22  19:55:19:973            T   IXN22QKB29000           126
74892  15-04-22  19:57:59:735            T   IXN22QKB31500           126
74913  15-04-22  19:58:13:982            T   IXN22QKB31500           126
74914  15-04-22  19:58:13:982            T   IXN22QKB31500           126
75035  15-04-22  19:59:03:511            T   IXN22QKB31000           126

      Security Type              Unknown Bid market Bid price Bid size  ...  \
4014              2  1407898818554001269     f2=6.6      f3=7  f108=23  ...
4015              2  1407898818554001275     f2=6.6      f3=7  f108=23  ...
5269              2  1407899243428000626     f2=3.2     f3=13  f108=23  ...
7184              2  1407901332122001206       f2=8      f3=2  f108=23  ...
8223              2  1407902161998202323    f2=19.5     f3=10  f108=23  ...
...             ...                  ...        ...       ...      ...  ...
74667             2  1407945039946000059     f2=7.4      f3=1  f108=23  ...
74892             2  1407945359470000503    f2=17.9      f3=1  f108=23  ...
74913             2  1407945387964001464    f2=17.9      f3=1  f108=23  ...
74914             2  1407945387964001466    f2=17.9      f3=7  f108=23  ...
75035             2  1407945487022000420    f2=15.3      f3=1  f108=23  ...

      Message Type4 Message Type5 Message Type6 Message Type7 Message Type8  \
4014        f17=6.6       f18=6.6       f19=6.6         f30=1         f16=7
4015         f16=14     f423=92.4      f243=6.6        f214=3          None
5269        f17=3.2       f18=3.2       f19=3.2         f30=1        f16=13
7184          f17=8         f18=8         f19=8         f30=1         f16=2
8223       f17=19.5      f18=19.5      f19=19.5         f30=1        f16=10
...             ...           ...           ...           ...           ...
74667         f30=4         f16=4     f423=28.3      f243=7.1       f214=15
74892        f16=12   f423=198.39     f243=16.5       f214=19          None
74913        f16=13   f423=216.29     f243=16.6       f214=19          None
74914        f16=20   f423=341.59     f243=17.1       f214=19          None
75035      f16=1497  f423=20856.7     f243=13.9       f214=14          None

      Message Type9 Message Type9 Message Type9 Message Type9 Message Type9
4014      f423=46.2      f243=6.6        f214=3          None          None
4015           None          None          None          None          None
5269      f423=41.6      f243=3.2       f214=34          None          None
7184        f423=16        f243=8        f214=3          None          None
8223       f423=195     f243=19.5       f214=14          None          None
...             ...           ...           ...           ...           ...
74667          None          None          None          None          None
74892          None          None          None          None          None
74913          None          None          None          None          None
74914          None          None          None          None          None
75035          None          None          None          None          None

[401 rows x 26 columns]

In [6]:
R = pd.read_csv("PerfectTdata.csv")
R

,Date,Time,Message Type,Instrument code,Exchange Code,Security Type,Unknown,Last price,Last volume,Bit flag to updated,...,RT of last update in Seconds,Yesterdays close price,Open price,High price,Low pric,of trades since market opening,Cumulative volume,Calculated Turnover,VWAP price,Origination market of last trade for composite updates
0,15/04/2022,13:30:09:277,T,IXN22FHB34000,126,2,1.410000e+18,f2=6.6,f3=7,f108=23,...,f943=9:30:9.0,f20=7.55,f17=6.6,f18=6.6,f19=6.6,f30=1,f16=7,f423=46.2,f243=6.6,f214=3
1,15/04/2022,13:30:09:277,T,IXN22FHB34000,126,2,1.410000e+18,f2=6.6,f3=7,f108=23,...,f943=9:30:9.0,NaN,NaN,NaN,NaN,f30=2,f16=14,f423=92.4,f243=6.6,f214=3
2,15/04/2022,13:33:41:714,T,IXN22QKB28000,126,2,1.410000e+18,f2=3.2,f3=13,f108=23,...,f943=9:33:41.0,f20=3.21,f17=3.2,f18=3.2,f19=3.2,f30=1,f16=13,f423=41.6,f243=3.2,f214=34
3,15/04/2022,13:51:06:061,T,IXN22FHB33500,126,2,1.410000e+18,f2=8,f3=2,f108=23,...,f943=9:51:6.0,f20=9.6,f17=8,f18=8,f19=8,f30=1,f16=2,f423=16,f243=8,f214=3
4,15/04/2022,13:58:00:999,T,IXN22UGB30000,126,2,1.410000e+18,f2=19.5,f3=10,f108=23,...,f943=9:58:0.0,f20=17.4,f17=19.5,f18=19.5,f19=19.5,f30=1,f16=10,f423=195,f243=19.5,f214=14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,15/04/2022,19:55:19:973,T,IXN22QKB29000,126,2,1.410000e+18,f2=7.4,f3=1,f108=23,...,f943=15:55:19.0,NaN,NaN,f18=7.4,NaN,f30=4,f16=4,f423=28.3,f243=7.1,f214=15
397,15/04/2022,19:57:59:735,T,IXN22QKB31500,126,2,1.410000e+18,f2=17.9,f3=1,f108=23,...,f943=15:57:59.0,NaN,NaN,NaN,NaN,f30=8,f16=12,f423=198.39,f243=16.5,f214=19
398,15/04/2022,19:58:13:982,T,IXN22QKB31500,126,2,1.410000e+18,f2=17.9,f3=1,f108=23,...,f943=15:58:13.0,NaN,NaN,NaN,NaN,f30=9,f16=13,f423=216.29,f243=16.6,f214=19
399,15/04/2022,19:58:13:982,T,IXN22QKB31500,126,2,1.410000e+18,f2=17.9,f3=7,f108=23,...,f943=15:58:13.0,NaN,NaN,NaN,NaN,f30=10,f16=20,f423=341.59,f243=17.1,f214=19
400,15/04/2022,19:59:03:511,T,IXN22QKB31000,126,2,1.410000e+18,f2=15.3,f3=1,f108=23,...,f943=15:59:3.0,NaN,NaN,NaN,NaN,f30=153,f16=1497,f423=20856.7,f243=13.9,f214=14

In [7]:
R = pd.read_csv("perfectTdata.csv")
R
# List of columns to remove first three characters from
columns_to_modify = ['Last price', 'Last volume']

# Remove first three characters from specified columns
for col in columns_to_modify:
    R[col] = R[col].str[3:]

# Display the resulting DataFrame
print(R)

           Date          Time Message Type Instrument code  Exchange Code  \
0    15/04/2022  13:30:09:277            T   IXN22FHB34000            126
1    15/04/2022  13:30:09:277            T   IXN22FHB34000            126
2    15/04/2022  13:33:41:714            T   IXN22QKB28000            126
3    15/04/2022  13:51:06:061            T   IXN22FHB33500            126
4    15/04/2022  13:58:00:999            T   IXN22UGB30000            126
..          ...           ...          ...             ...            ...
396  15/04/2022  19:55:19:973            T   IXN22QKB29000            126
397  15/04/2022  19:57:59:735            T   IXN22QKB31500            126
398  15/04/2022  19:58:13:982            T   IXN22QKB31500            126
399  15/04/2022  19:58:13:982            T   IXN22QKB31500            126
400  15/04/2022  19:59:03:511            T   IXN22QKB31000            126

     Security Type       Unknown Last price Last volume Bit flag to updated  \
0                2  1.410000e+18        6.6           7             f108=23
1                2  1.410000e+18        6.6           7             f108=23
2                2  1.410000e+18        3.2          13             f108=23
3                2  1.410000e+18          8           2             f108=23
4                2  1.410000e+18       19.5          10             f108=23
..             ...           ...        ...         ...                 ...
396              2  1.410000e+18        7.4           1             f108=23
397              2  1.410000e+18       17.9           1             f108=23
398              2  1.410000e+18       17.9           1             f108=23
399              2  1.410000e+18       17.9           7             f108=23
400              2  1.410000e+18       15.3           1             f108=23

     ... RT of last update in Seconds Yesterdays close price Open price  \
0    ...                f943=9:30:9.0               f20=7.55    f17=6.6
1    ...                f943=9:30:9.0                    NaN        NaN
2    ...               f943=9:33:41.0               f20=3.21    f17=3.2
3    ...                f943=9:51:6.0                f20=9.6      f17=8
4    ...                f943=9:58:0.0               f20=17.4   f17=19.5
..   ...                          ...                    ...        ...
396  ...              f943=15:55:19.0                    NaN        NaN
397  ...              f943=15:57:59.0                    NaN        NaN
398  ...              f943=15:58:13.0                    NaN        NaN
399  ...              f943=15:58:13.0                    NaN        NaN
400  ...               f943=15:59:3.0                    NaN        NaN

    High price  Low pric of trades since market opening Cumulative volume  \
0      f18=6.6   f19=6.6                          f30=1             f16=7
1          NaN       NaN                          f30=2            f16=14
2      f18=3.2   f19=3.2                          f30=1            f16=13
3        f18=8     f19=8                          f30=1             f16=2
4     f18=19.5  f19=19.5                          f30=1            f16=10
..         ...       ...                            ...               ...
396    f18=7.4       NaN                          f30=4             f16=4
397        NaN       NaN                          f30=8            f16=12
398        NaN       NaN                          f30=9            f16=13
399        NaN       NaN                         f30=10            f16=20
400        NaN       NaN                        f30=153          f16=1497

    Calculated Turnover VWAP price  \
0             f423=46.2   f243=6.6
1             f423=92.4   f243=6.6
2             f423=41.6   f243=3.2
3               f423=16     f243=8
4              f423=195  f243=19.5
..                  ...        ...
396           f423=28.3   f243=7.1
397         f423=198.39  f243=16.5
398         f423=216.29  f243=16.6
399         f423=341.59  f243=17.1
400        f423=20856.7  f243=13.9

    Origination market of last trade for composite updates
0                                               f214=3
1                                               f214=3
2                                              f214=34
3                                               f214=3
4                                              f214=14
..                                                 ...
396                                            f214=15
397                                            f214=19
398                                            f214=19
399                                            f214=19
400                                            f214=14

[401 rows x 24 columns]

In [8]:
R1=R

# List of columns to remove first three characters from
columns_to_modify = ['Yesterdays close price', 'Open price', 'High price','Low pric', 'of trades since market opening','Cumulative volume']

# Remove first three characters from specified columns
for col in columns_to_modify:
    R[col] = R[col].str[4:]

# Display the resulting DataFrame
print(R1)

           Date          Time Message Type Instrument code  Exchange Code  \
0    15/04/2022  13:30:09:277            T   IXN22FHB34000            126
1    15/04/2022  13:30:09:277            T   IXN22FHB34000            126
2    15/04/2022  13:33:41:714            T   IXN22QKB28000            126
3    15/04/2022  13:51:06:061            T   IXN22FHB33500            126
4    15/04/2022  13:58:00:999            T   IXN22UGB30000            126
..          ...           ...          ...             ...            ...
396  15/04/2022  19:55:19:973            T   IXN22QKB29000            126
397  15/04/2022  19:57:59:735            T   IXN22QKB31500            126
398  15/04/2022  19:58:13:982            T   IXN22QKB31500            126
399  15/04/2022  19:58:13:982            T   IXN22QKB31500            126
400  15/04/2022  19:59:03:511            T   IXN22QKB31000            126

     Security Type       Unknown Last price Last volume Bit flag to updated  \
0                2  1.410000e+18        6.6           7             f108=23
1                2  1.410000e+18        6.6           7             f108=23
2                2  1.410000e+18        3.2          13             f108=23
3                2  1.410000e+18          8           2             f108=23
4                2  1.410000e+18       19.5          10             f108=23
..             ...           ...        ...         ...                 ...
396              2  1.410000e+18        7.4           1             f108=23
397              2  1.410000e+18       17.9           1             f108=23
398              2  1.410000e+18       17.9           1             f108=23
399              2  1.410000e+18       17.9           7             f108=23
400              2  1.410000e+18       15.3           1             f108=23

     ... RT of last update in Seconds Yesterdays close price Open price  \
0    ...                f943=9:30:9.0                   7.55        6.6
1    ...                f943=9:30:9.0                    NaN        NaN
2    ...               f943=9:33:41.0                   3.21        3.2
3    ...                f943=9:51:6.0                    9.6          8
4    ...                f943=9:58:0.0                   17.4       19.5
..   ...                          ...                    ...        ...
396  ...              f943=15:55:19.0                    NaN        NaN
397  ...              f943=15:57:59.0                    NaN        NaN
398  ...              f943=15:58:13.0                    NaN        NaN
399  ...              f943=15:58:13.0                    NaN        NaN
400  ...               f943=15:59:3.0                    NaN        NaN

    High price Low pric of trades since market opening Cumulative volume  \
0          6.6      6.6                              1                 7
1          NaN      NaN                              2                14
2          3.2      3.2                              1                13
3            8        8                              1                 2
4         19.5     19.5                              1                10
..         ...      ...                            ...               ...
396        7.4      NaN                              4                 4
397        NaN      NaN                              8                12
398        NaN      NaN                              9                13
399        NaN      NaN                             10                20
400        NaN      NaN                            153              1497

    Calculated Turnover VWAP price  \
0             f423=46.2   f243=6.6
1             f423=92.4   f243=6.6
2             f423=41.6   f243=3.2
3               f423=16     f243=8
4              f423=195  f243=19.5
..                  ...        ...
396           f423=28.3   f243=7.1
397         f423=198.39  f243=16.5
398         f423=216.29  f243=16.6
399         f423=341.59  f243=17.1
400        f423=20856.7  f243=13.9

    Origination market of last trade for composite updates
0                                               f214=3
1                                               f214=3
2                                              f214=34
3                                               f214=3
4                                              f214=14
..                                                 ...
396                                            f214=15
397                                            f214=19
398                                            f214=19
399                                            f214=19
400                                            f214=14

[401 rows x 24 columns]

In [9]:
R2=R1

# List of columns to remove first three characters from
columns_to_modify = ['Bit flag to updated', 'Trade indicator flag', 'RT of Last Trade in Seconds','Julian Date of last Trade', 'RT of last update in Seconds','Calculated Turnover','VWAP price','Origination market of last trade for composite updates']

# Remove first three characters from specified columns
for col in columns_to_modify:
    R1[col] = R1[col].str[5:]

# Display the resulting DataFrame
print(R2)

           Date          Time Message Type Instrument code  Exchange Code  \
0    15/04/2022  13:30:09:277            T   IXN22FHB34000            126
1    15/04/2022  13:30:09:277            T   IXN22FHB34000            126
2    15/04/2022  13:33:41:714            T   IXN22QKB28000            126
3    15/04/2022  13:51:06:061            T   IXN22FHB33500            126
4    15/04/2022  13:58:00:999            T   IXN22UGB30000            126
..          ...           ...          ...             ...            ...
396  15/04/2022  19:55:19:973            T   IXN22QKB29000            126
397  15/04/2022  19:57:59:735            T   IXN22QKB31500            126
398  15/04/2022  19:58:13:982            T   IXN22QKB31500            126
399  15/04/2022  19:58:13:982            T   IXN22QKB31500            126
400  15/04/2022  19:59:03:511            T   IXN22QKB31000            126

     Security Type       Unknown Last price Last volume Bit flag to updated  \
0                2  1.410000e+18        6.6           7                  23
1                2  1.410000e+18        6.6           7                  23
2                2  1.410000e+18        3.2          13                  23
3                2  1.410000e+18          8           2                  23
4                2  1.410000e+18       19.5          10                  23
..             ...           ...        ...         ...                 ...
396              2  1.410000e+18        7.4           1                  23
397              2  1.410000e+18       17.9           1                  23
398              2  1.410000e+18       17.9           1                  23
399              2  1.410000e+18       17.9           7                  23
400              2  1.410000e+18       15.3           1                  23

     ... RT of last update in Seconds Yesterdays close price Open price  \
0    ...                     9:30:9.0                   7.55        6.6
1    ...                     9:30:9.0                    NaN        NaN
2    ...                    9:33:41.0                   3.21        3.2
3    ...                     9:51:6.0                    9.6          8
4    ...                     9:58:0.0                   17.4       19.5
..   ...                          ...                    ...        ...
396  ...                   15:55:19.0                    NaN        NaN
397  ...                   15:57:59.0                    NaN        NaN
398  ...                   15:58:13.0                    NaN        NaN
399  ...                   15:58:13.0                    NaN        NaN
400  ...                    15:59:3.0                    NaN        NaN

    High price Low pric of trades since market opening Cumulative volume  \
0          6.6      6.6                              1                 7
1          NaN      NaN                              2                14
2          3.2      3.2                              1                13
3            8        8                              1                 2
4         19.5     19.5                              1                10
..         ...      ...                            ...               ...
396        7.4      NaN                              4                 4
397        NaN      NaN                              8                12
398        NaN      NaN                              9                13
399        NaN      NaN                             10                20
400        NaN      NaN                            153              1497

    Calculated Turnover VWAP price  \
0                  46.2        6.6
1                  92.4        6.6
2                  41.6        3.2
3                    16          8
4                   195       19.5
..                  ...        ...
396                28.3        7.1
397              198.39       16.5
398              216.29       16.6
399              341.59       17.1
400             20856.7       13.9

    Origination market of last trade for composite updates
0                                                    3
1                                                    3
2                                                   34
3                                                    3
4                                                   14
..                                                 ...
396                                                 15
397                                                 19
398                                                 19
399                                                 19
400                                                 14

[401 rows x 24 columns]

In [10]:
R3=R2

# List of columns to remove first three characters from
columns_to_modify = ['Source of realtime message']
# Remove first three characters from specified columns
for col in columns_to_modify:
    R2[col] = R2[col].str[6:]

# Display the resulting DataFrame
print(R3)

           Date          Time Message Type Instrument code  Exchange Code  \
0    15/04/2022  13:30:09:277            T   IXN22FHB34000            126
1    15/04/2022  13:30:09:277            T   IXN22FHB34000            126
2    15/04/2022  13:33:41:714            T   IXN22QKB28000            126
3    15/04/2022  13:51:06:061            T   IXN22FHB33500            126
4    15/04/2022  13:58:00:999            T   IXN22UGB30000            126
..          ...           ...          ...             ...            ...
396  15/04/2022  19:55:19:973            T   IXN22QKB29000            126
397  15/04/2022  19:57:59:735            T   IXN22QKB31500            126
398  15/04/2022  19:58:13:982            T   IXN22QKB31500            126
399  15/04/2022  19:58:13:982            T   IXN22QKB31500            126
400  15/04/2022  19:59:03:511            T   IXN22QKB31000            126

     Security Type       Unknown Last price Last volume Bit flag to updated  \
0                2  1.410000e+18        6.6           7                  23
1                2  1.410000e+18        6.6           7                  23
2                2  1.410000e+18        3.2          13                  23
3                2  1.410000e+18          8           2                  23
4                2  1.410000e+18       19.5          10                  23
..             ...           ...        ...         ...                 ...
396              2  1.410000e+18        7.4           1                  23
397              2  1.410000e+18       17.9           1                  23
398              2  1.410000e+18       17.9           1                  23
399              2  1.410000e+18       17.9           7                  23
400              2  1.410000e+18       15.3           1                  23

     ... RT of last update in Seconds Yesterdays close price Open price  \
0    ...                     9:30:9.0                   7.55        6.6
1    ...                     9:30:9.0                    NaN        NaN
2    ...                    9:33:41.0                   3.21        3.2
3    ...                     9:51:6.0                    9.6          8
4    ...                     9:58:0.0                   17.4       19.5
..   ...                          ...                    ...        ...
396  ...                   15:55:19.0                    NaN        NaN
397  ...                   15:57:59.0                    NaN        NaN
398  ...                   15:58:13.0                    NaN        NaN
399  ...                   15:58:13.0                    NaN        NaN
400  ...                    15:59:3.0                    NaN        NaN

    High price Low pric of trades since market opening Cumulative volume  \
0          6.6      6.6                              1                 7
1          NaN      NaN                              2                14
2          3.2      3.2                              1                13
3            8        8                              1                 2
4         19.5     19.5                              1                10
..         ...      ...                            ...               ...
396        7.4      NaN                              4                 4
397        NaN      NaN                              8                12
398        NaN      NaN                              9                13
399        NaN      NaN                             10                20
400        NaN      NaN                            153              1497

    Calculated Turnover VWAP price  \
0                  46.2        6.6
1                  92.4        6.6
2                  41.6        3.2
3                    16          8
4                   195       19.5
..                  ...        ...
396                28.3        7.1
397              198.39       16.5
398              216.29       16.6
399              341.59       17.1
400             20856.7       13.9

    Origination market of last trade for composite updates
0                                                    3
1                                                    3
2                                                   34
3                                                    3
4                                                   14
..                                                 ...
396                                                 15
397                                                 19
398                                                 19
399                                                 19
400                                                 14

[401 rows x 24 columns]

In [18]:
R3.to_csv('Rdata.csv', index=False)

In [19]:
print(R3['Open interest'].dtypes)

KeyError: 'Open interest'